<?php
/**
 * PassApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Demo Client for Passmeister Apple Wallet and Google Wallet API
 *
 * [www.passmeister.com](https://www.passmeister.com).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PassApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PassApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrUpdatePass
     *
     * This method creates or (if the pass id already exists) updates a pass, so you don't have to track ids and creation status of your passes..
     *
     */
    public function testCreateOrUpdatePass()
    {
    }

    /**
     * Test case for deletePass
     *
     * Delete pass by pass id..
     *
     */
    public function testDeletePass()
    {
    }

    /**
     * Test case for getPass
     *
     * Get pass information by pass id..
     *
     */
    public function testGetPass()
    {
    }

    /**
     * Test case for passList
     *
     * Retrieve the list of active pass ids for a given pass type..
     *
     */
    public function testPassList()
    {
    }

    /**
     * Test case for passSync
     *
     * Send updates to all active passes for a given pass type..
     *
     */
    public function testPassSync()
    {
    }
}
